# Generated by Django 4.2 on 2024-01-07 20:57

import uuid

import django.db.models.deletion
from django.db import migrations, models

import towns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TownImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=towns.models.town_image_path)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towns.town')),
            ],
        ),
        migrations.CreateModel(
            name='TownAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='towns.town')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=towns.models.attraction_image_path)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towns.townattraction')),
            ],
        ),
    ]
