# Generated by Django 4.2 on 2024-01-08 11:21

import django.db.models.deletion
from django.db import migrations, models

import towns.models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractionimage',
            options={'verbose_name': 'Фотография достопримечательности', 'verbose_name_plural': 'Фотографии достопримечательности'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='townattraction',
            options={'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
        migrations.AlterModelOptions(
            name='townimage',
            options={'verbose_name': 'Фотография населенного пункта', 'verbose_name_plural': 'Фотография населенного пункта'},
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towns.townattraction', verbose_name='Достопримечательнось'),
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to=towns.models.attraction_image_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='town',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='townattraction',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='townattraction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='townattraction',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='towns.town', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='townimage',
            name='image',
            field=models.ImageField(upload_to=towns.models.town_image_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='townimage',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towns.town', verbose_name='Населенный пункт'),
        ),
    ]
