# Generated by Django 4.2 on 2024-01-10 21:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCottageLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Понравившийся коттедж',
                'verbose_name_plural': 'Понравившиеся коттеджи',
            },
        ),
        migrations.CreateModel(
            name='UserCottageRent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
            ],
            options={
                'verbose_name': 'Аренда коттеджа',
                'verbose_name_plural': 'Аренды коттеджа',
            },
        ),
        migrations.CreateModel(
            name='UserCottageReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cottage_rating', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг коттеджа')),
                ('cleanliness_rating', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг чистоты')),
                ('owner_rating', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг хозяина')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Отзыв коттеджа',
                'verbose_name_plural': 'Отзывы коттеджа',
            },
        ),
    ]
