# Generated by Django 4.2 on 2024-01-08 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0002_alter_cottage_options_alter_cottageamenities_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercottagelike',
            options={'verbose_name': 'Понравившийся коттедж', 'verbose_name_plural': 'Понравившиеся коттеджи'},
        ),
        migrations.AlterModelOptions(
            name='usercottagerent',
            options={'verbose_name': 'Аренда коттеджа', 'verbose_name_plural': 'Аренды коттеджа'},
        ),
        migrations.AlterModelOptions(
            name='usercottagereview',
            options={'verbose_name': 'Отзыв коттеджа', 'verbose_name_plural': 'Отзывы коттеджа'},
        ),
        migrations.AlterField(
            model_name='usercottagelike',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='usercottagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usercottagerent',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='usercottagerent',
            name='end_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='usercottagerent',
            name='start_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='usercottagerent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='cleanliness_rating',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг чистоты'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='comment',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='cottage_rating',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг коттеджа'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='owner_rating',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг хозяина'),
        ),
        migrations.AlterField(
            model_name='usercottagereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
