# Generated by Django 4.2 on 2024-01-10 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations', '0001_initial'),
        ('cottages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercottagereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usercottagerent',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AddField(
            model_name='usercottagerent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usercottagelike',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AddField(
            model_name='usercottagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
