# Generated by Django 4.2 on 2024-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercottagerent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Оплачен'), (3, 'Отказ'), (3, 'Подтвержден')], default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
