# Generated by Django 4.2 on 2024-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_usercottagerent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercottagereview',
            name='rating',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
