# Generated by Django 4.2 on 2024-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_alter_usercottagereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercottagerent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Оплачен'), (3, 'Отказ'), (4, 'Подтвержден')], verbose_name='Статус'),
        ),
    ]
