# Generated by Django 4.2 on 2024-06-09 07:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relations', '0004_alter_usercottagereview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ukassa', models.CharField(db_index=True, max_length=100)),
                ('redirect_url', models.URLField(db_index=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.CharField(db_index=True, max_length=100)),
                ('ukassa_response', models.JSONField(db_index=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='relations.usercottagerent')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
