# Generated by Django 4.2 on 2024-06-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ukassa',
            new_name='ukassa_id',
        ),
    ]
