# Generated by Django 4.2 on 2024-06-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_ukassa_payment_ukassa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
