# Generated by Django 4.2 on 2024-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rentier',
            field=models.BooleanField(default=False, verbose_name='Арендодатель'),
        ),
    ]
