# Generated by Django 4.2 on 2024-06-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verifycode_user_photo_delete_emailverification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
