# Generated by Django 4.2 on 2024-01-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Email подтверждение', 'verbose_name_plural': 'Email подтверждения'},
        ),
    ]
