# Generated by Django 4.2 on 2024-06-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='action',
        ),
    ]
