# Generated by Django 4.2 on 2024-01-18 16:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import cottages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Цена')),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во гостей')),
                ('beds', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Кол-во кроватей')),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Кол-во комнат')),
                ('total_area', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Общая площадь')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Коттедж',
                'verbose_name_plural': 'Коттеджи',
            },
        ),
        migrations.CreateModel(
            name='CottageCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CottageRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.TimeField(verbose_name='Время заезда')),
                ('check_out_time', models.TimeField(verbose_name='Время выезда')),
                ('with_children', models.BooleanField(default=True, verbose_name='С детьми')),
                ('with_pets', models.BooleanField(default=False, verbose_name='С животными')),
                ('smoking', models.BooleanField(default=False, verbose_name='Курение')),
                ('parties', models.BooleanField(default=True, verbose_name='Вечеринки')),
                ('need_documents', models.BooleanField(default=True, verbose_name='Необходимость документов')),
                ('cottage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Правила коттеджа',
                'verbose_name_plural': 'Правила коттеджа',
            },
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=cottages.models.cottage_image_path, verbose_name='Фотография')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Фотография коттеджа',
                'verbose_name_plural': 'Фотографии коттеджа',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CottageAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parking_spaces', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во парковочных мест')),
                ('wifi', models.BooleanField(default=False, verbose_name='Вай-фай')),
                ('tv', models.BooleanField(default=False, verbose_name='Телевизор')),
                ('air_conditioner', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('hair_dryer', models.BooleanField(default=False, verbose_name='Фен')),
                ('electric_kettle', models.BooleanField(default=False, verbose_name='Электрический чайник')),
                ('cottage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Удобства коттеджа',
                'verbose_name_plural': 'Удобства коттеджа',
            },
        ),
        migrations.AddField(
            model_name='cottage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottagecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town', verbose_name='Населенный пункт'),
        ),
    ]
