# Generated by Django 4.2 on 2024-01-07 20:57

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cottages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('beds', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('total_area', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='CottageCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CottageRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('with_children', models.BooleanField(default=True)),
                ('with_pets', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('parties', models.BooleanField(default=True)),
                ('need_documents', models.BooleanField(default=True)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottage')),
            ],
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=cottages.models.cottage_image_path)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage')),
            ],
        ),
        migrations.CreateModel(
            name='CottageAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parking_spaces', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('electric_kettle', models.BooleanField(default=False)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottage')),
            ],
        ),
        migrations.AddField(
            model_name='cottage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottagecategory'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
