# Generated by Django 4.2 on 2024-01-08 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cottages.models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_alter_attractionimage_options_alter_town_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottage',
            options={'verbose_name': 'Коттедж', 'verbose_name_plural': 'Коттеджи'},
        ),
        migrations.AlterModelOptions(
            name='cottageamenities',
            options={'verbose_name': 'Удобства коттеджа', 'verbose_name_plural': 'Удобства коттеджа'},
        ),
        migrations.AlterModelOptions(
            name='cottagecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cottageimage',
            options={'verbose_name': 'Фотография коттеджа', 'verbose_name_plural': 'Фотографии коттеджа'},
        ),
        migrations.AlterModelOptions(
            name='cottagerules',
            options={'verbose_name': 'Правила коттеджа', 'verbose_name_plural': 'Правила коттеджа'},
        ),
        migrations.AlterField(
            model_name='cottage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='beds',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Кол-во кроватей'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottagecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='total_area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='air_conditioner',
            field=models.BooleanField(default=False, verbose_name='Кондиционер'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='electric_kettle',
            field=models.BooleanField(default=False, verbose_name='Электрический чайник'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='hair_dryer',
            field=models.BooleanField(default=False, verbose_name='Фен'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='parking_spaces',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во парковочных мест'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='Телевизор'),
        ),
        migrations.AlterField(
            model_name='cottageamenities',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Вай-фай'),
        ),
        migrations.AlterField(
            model_name='cottagecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cottageimage',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='cottageimage',
            name='image',
            field=models.ImageField(upload_to=cottages.models.cottage_image_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='check_in_time',
            field=models.TimeField(verbose_name='Время заезда'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='check_out_time',
            field=models.TimeField(verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='cottage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cottages.cottage', verbose_name='Коттедж'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='need_documents',
            field=models.BooleanField(default=True, verbose_name='Необходимость документов'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='parties',
            field=models.BooleanField(default=True, verbose_name='Вечеринки'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='Курение'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='with_children',
            field=models.BooleanField(default=True, verbose_name='С детьми'),
        ),
        migrations.AlterField(
            model_name='cottagerules',
            name='with_pets',
            field=models.BooleanField(default=False, verbose_name='С животными'),
        ),
    ]
