# Generated by Django 4.2 on 2024-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
