# Generated by Django 4.2 on 2024-01-06 13:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import cottages.models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0002_alter_cottage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='options',
            field=models.JSONField(default=dict, validators=[cottages.models.validate_options]),
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.cottage')),
            ],
        ),
    ]
