# Generated by Django 4.2 on 2024-01-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0002_alter_cottage_options_alter_cottageamenities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottageamenities',
            name='cottage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='cottages.cottage', verbose_name='Коттедж'),
        ),
    ]
