# Generated by Django 4.2 on 2024-06-11 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
        ('cottages', '0002_alter_cottage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='amenities',
            field=models.JSONField(blank=True, null=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='beds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Кол-во кроватей'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время заезда'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='guests',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='parking_places',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во парковочных мест'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='rules',
            field=models.JSONField(blank=True, null=True, verbose_name='Правила'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='towns.town', verbose_name='Населенный пункт'),
        ),
    ]
