# Generated by Django 4.2 on 2024-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0003_alter_cottage_amenities_alter_cottage_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='is_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
