# Generated by Django 4.2 on 2024-01-06 14:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0003_alter_cottage_options_cottageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottageimage',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage'),
        ),
        migrations.CreateModel(
            name='CottageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cottages.cottage')),
            ],
        ),
    ]
