# Generated by Django 4.2 on 2024-01-06 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cottages', '0004_alter_cottageimage_cottage_cottagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagecomment',
            name='user',
            field=models.ForeignKey(default='6f96229c-1f6e-446c-8a74-d4215dfddc41', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
