# Generated by Django 4.2 on 2024-01-06 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0005_cottagecomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottagecomment',
            name='rating',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
