# Generated by Django 4.2 on 2024-01-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0006_cottagecomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='price',
            field=models.PositiveSmallIntegerField(default=13000, max_length=5),
            preserve_default=False,
        ),
    ]
