# Generated by Django 4.2 on 2024-01-06 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0007_cottage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
